### ISSUE TITLE
Which Python/PyTorch/CUDA version should we use?

### ISSUE THREAD

**Issue by alcunha** [RolnickLab/ami-ml#1]
I think it is important to set at least the Python and PyTorch version at the beginning to avoid problems later when migrating to newer versions.

Should we start using PyTorch 2.0?

**Comment by leonardpasi** [comment]
I have been using PyTorch 2.0 and python 3.9, but I don't see any reason not to use the latest python 3.11, which is supposedly x1.25 faster on average

**Comment by mihow** [comment]
I've been using Python 3.11 and enjoying it! The tracebacks are a little more helpful, and there are some new typing annotations. 

I opened a PR that uses Poetry for managing dependencies. Can we try and maintain a common set of dependencies for all scripts & sub-projects? If some projects require many more then you can use groups to manage dependencies, or make some dependencies optional. You can also define scripts to the pyproject.toml.

For example:

`poetry install --without GUI`
`poetry install --without dev`

or `poetry install --group audio`

But hopefully we have mostly shared dependencies and can use the same steps for all sub-projects

```
poetry install
poetry shell
python src/gbif/fetch_sample.y
python src/classification/main.py
```
