### ISSUE TITLE
Global Moth Model

### ISSUE THREAD

**Issue by adityajain07** [RolnickLab/ami-ml#18]
A global moth species classifier

**Comment by joseepoirier** [comment]
@adityajain07 Will you break up this issue into more issues, or have multiple tasks within this issue? I would recommend the former.

**Comment by adityajain07** [comment]
Sure! Here it is:
1. Prepare, analyze and verify the global moth checklist from GBIF
2. Prepare the webdataset with the latest DwC-A file
3. Train model

**Comment by joseepoirier** [comment]
Following a conversation between AJ and DR, this model is the top priority from 23 Jul.

**Comment by adityajain07** [comment]
Code profilings to be done:

- [ ] Uploading category map to W&B
- [ ] Make the training code into a cli, like the ami-dataset module
- [ ] Documentation
- [ ] Check for preemption; resume training from last saved point
- [ ] Test the code (with breakpoints) with a smaller dataset

**Comment by joseepoirier** [comment]
Thanks for adding the code-profiling tasks above! How are you prioritising them with respect to the data prep/model training above?
