### ISSUE TITLE
Which directory structure should we use?

### ISSUE THREAD

**Issue by alcunha** [RolnickLab/ami-ml#2]
At the top level should we create a folder for each main task on AMI framework?

- classification
- detection
- segmentation
- tracking

**Comment by joseepoirier** [comment]
@alcunha This doesn't seem to have been resolved. Do you have a recommendation as we accelerate ML implementation work?

@f-PLT @mihow Any thoughts?

**Comment by mihow** [comment]
I think we did resolve this in a conversation! We start implementing in the /src folder. The current directories are:

```
./src/dataset_tools/
./src/localization/
```

and then coming soon is:

```
./src/classification/
```

The only thing we could consider changing is adding an `ami_ml` folder under `./src` to help with importing during local development. @f-PLT thoughts on how important that is? I would rename the files in the git history as well if we do that.

**Comment by f-PLT** [comment]
I'd be in the "rename src to ami_ml" for the reasons mentioned by @mihow as it's pretty common practice.

Not sure how important rewriting the git history would be though given the scale of the project and the small number of commits. I'd definitely merge currently opened pull requests before doing so (whether we rewrite git history or not)

**Comment by joseepoirier** [comment]
Can this issue be resolved? If not, what is left?
